services:
  go-dairy:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - config.env
    networks:
      - go-dairy-network
  
  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - go-dairy-pgdata:/var/lib/postgresql/data
    env_file:
      - config.env

volumes:
  pgdata:
    driver: local

networks:
  go-dairy-network:
    driver: bridge