name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: remote docker-compose up via ssh
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USERNAME }}
          pass: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          connect_timeout: 10s
          first_ssh: |
            git clone https://github.com/${{ github.repository }} ~/.deploy/${{ github.event.repository.name }}
            cd ~/.deploy/${{ github.event.repository.name }}
            git checkout ${{ github.event.inputs.tag }}
            docker compose -f ./docker-compose.yaml pull
            docker compose -f ./docker-compose.yaml -f up -d