name: Deploy App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            git clone --branch ${{ github.event.inputs.tag }} https://github.com/${{ github.repository }} ~/.deploy/${{ github.event.repository.name }}
            cd ~/.deploy/${{ github.event.repository.name }}
            docker compose -f ./docker-compose.yml pull
            docker compose -f ./docker-compose.yml -f up -d